version: '3.4'

services:
  employeesdb:
    container_name: employeesdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  employees.api:
    container_name: employees.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://employeesdb:27017"
    depends_on:
      - employeesdb
    ports:
      - "8000:80"
