version: '3.4'

services:
  employeesdb:
    container_name: employeesdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  skillsdb:
    container_name: skillsdb
    restart: always
    ports:
      - "6379:6379"

  crmdb:
    container_name: crmdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=CrmDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  erpdb:
    container_name: erpdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=ErpDb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_data2:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment: 
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0.
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  employees.api:
    container_name: employees.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://employeesdb:27017"
    depends_on:
      - employeesdb
    ports:
      - "8000:80"

  skills.api:
    container_name: skills.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=skillsdb:6379"
    depends_on:
      - skillsdb
    ports:
      - "8001:80"


  crm.api:
    container_name: crm.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=crmdb;Port=5432;Database=CrmDb;User Id=admin;Password=admin1234;"
    depends_on:
      - crmdb
    ports:
      - "8002:80"


  erp.api:
    container_name: erp.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=erpdb;Port=5432;Database=ErpDb;User Id=admin;Password=admin1234;"
    depends_on:
      - erpdb
    ports:
      - "8003:80"


  audit.api:
    container_name: audit.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CrmUrl=http://crm.api"
      - "ApiSettings:ErpUrl=http://erp.api"
    depends_on:
      - erp.api
      - crm.api
    ports:
      - "8004:80"

  opportunity.api:
    container_name: opportunity.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:EmployeesUrl=http://employees.api"
      - "ApiSettings:SkillsUrl=http://skills.api"
      - "ApiSettings:CrmUrl=http://crm.api"
    depends_on:
      - employees.api
      - skills.api
      - crm.api
    ports:
      - "8005:80"


  requestforquote.api:
    container_name: requestforquote.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:AuditUrl=http://audit.api"
      - "ApiSettings:OpportunityUrl=http://opportunity.api"
    depends_on:
      - audit.api
      - opportunity.api
    ports:
      - "8006:80"

